<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DataModel\DataModel.csproj" />
    <ProjectReference Include="..\Communicator\Communicator.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Polly" Version="8.6.1" />
  </ItemGroup>
</Project>